import Head from "next/head";
import Main from "../components/Main";

export default function Home() {
  return (
    <div className="container">
      <Head>
        <title>Technical Task</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="stylesheet"
          href="https://unpkg.com/swiper@7/swiper-bundle.min.css"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main />
    </div>
  );
}
